# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f58d2dcc2be50c7aefa5eace4f4c276ff763080cbd1b4946fc2159c4d4bcba2479559a246e8448f17e4ae84897619a3f02ceeaace4dd134f054a4aa46e081a4

test:
  secret_key_base: c67e0679311ed1f7691ad04aba2ac2ab78aca6d05f9330ab004fa841f018482ce6204f68f0ce541b96bd71d1f5c0c6c9e823f332c052726a8055519879b5de59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
